export const countriesList = [
  {
    country: 'South Georgia',
    language: 'English',
    cca2: 'GS',
    ccn3: '239',
    cca3: 'SGS',
    currency: 'Saint Helena pound',
    currencySymbol: '£',
    currencyCode: 'SHP',
    flag: '🇬🇸',
  },
  {
    country: 'Grenada',
    language: 'English',
    cca2: 'GD',
    ccn3: '308',
    cca3: 'GRD',
    cioc: 'GRN',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇬🇩',
  },
  {
    country: 'Switzerland',
    language: 'French',
    cca2: 'CH',
    ccn3: '756',
    cca3: 'CHE',
    cioc: 'SUI',
    currency: 'Swiss franc',
    currencySymbol: 'Fr.',
    currencyCode: 'CHF',
    flag: '🇨🇭',
  },
  {
    country: 'Sierra Leone',
    language: 'English',
    cca2: 'SL',
    ccn3: '694',
    cca3: 'SLE',
    cioc: 'SLE',
    currency: 'Sierra Leonean leone',
    currencySymbol: 'Le',
    currencyCode: 'SLL',
    flag: '🇸🇱',
  },
  {
    country: 'Hungary',
    language: 'Hungarian',
    cca2: 'HU',
    ccn3: '348',
    cca3: 'HUN',
    cioc: 'HUN',
    currency: 'Hungarian forint',
    currencySymbol: 'Ft',
    currencyCode: 'HUF',
    flag: '🇭🇺',
  },
  {
    country: 'Taiwan',
    language: 'Chinese',
    cca2: 'TW',
    ccn3: '158',
    cca3: 'TWN',
    cioc: 'TPE',
    currency: 'New Taiwan dollar',
    currencySymbol: '$',
    currencyCode: 'TWD',
    flag: '🇹🇼',
  },
  {
    country: 'Wallis and Futuna',
    language: 'French',
    cca2: 'WF',
    ccn3: '876',
    cca3: 'WLF',
    currency: 'CFP franc',
    currencySymbol: '₣',
    currencyCode: 'XPF',
    flag: '🇼🇫',
  },
  {
    country: 'Barbados',
    language: 'English',
    cca2: 'BB',
    ccn3: '052',
    cca3: 'BRB',
    cioc: 'BAR',
    currency: 'Barbadian dollar',
    currencySymbol: '$',
    currencyCode: 'BBD',
    flag: '🇧🇧',
  },
  {
    country: 'Pitcairn Islands',
    language: 'English',
    cca2: 'PN',
    ccn3: '612',
    cca3: 'PCN',
    currency: 'New Zealand dollar',
    currencySymbol: '$',
    currencyCode: 'NZD',
    flag: '🇵🇳',
  },
  {
    country: 'Ivory Coast',
    language: 'French',
    cca2: 'CI',
    ccn3: '384',
    cca3: 'CIV',
    cioc: 'CIV',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇨🇮',
  },
  {
    country: 'Tunisia',
    language: 'Arabic',
    cca2: 'TN',
    ccn3: '788',
    cca3: 'TUN',
    cioc: 'TUN',
    currency: 'Tunisian dinar',
    currencySymbol: 'د.ت',
    currencyCode: 'TND',
    flag: '🇹🇳',
  },
  {
    country: 'Italy',
    language: 'Italian',
    cca2: 'IT',
    ccn3: '380',
    cca3: 'ITA',
    cioc: 'ITA',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇮🇹',
  },
  {
    country: 'Benin',
    language: 'French',
    cca2: 'BJ',
    ccn3: '204',
    cca3: 'BEN',
    cioc: 'BEN',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇧🇯',
  },
  {
    country: 'Indonesia',
    language: 'Indonesian',
    cca2: 'ID',
    ccn3: '360',
    cca3: 'IDN',
    cioc: 'INA',
    currency: 'Indonesian rupiah',
    currencySymbol: 'Rp',
    currencyCode: 'IDR',
    flag: '🇮🇩',
  },
  {
    country: 'Cape Verde',
    language: 'Portuguese',
    cca2: 'CV',
    ccn3: '132',
    cca3: 'CPV',
    cioc: 'CPV',
    currency: 'Cape Verdean escudo',
    currencySymbol: 'Esc',
    currencyCode: 'CVE',
    flag: '🇨🇻',
  },
  {
    country: 'Saint Kitts and Nevis',
    language: 'English',
    cca2: 'KN',
    ccn3: '659',
    cca3: 'KNA',
    cioc: 'SKN',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇰🇳',
  },
  {
    country: 'Laos',
    language: 'Lao',
    cca2: 'LA',
    ccn3: '418',
    cca3: 'LAO',
    cioc: 'LAO',
    currency: 'Lao kip',
    currencySymbol: '₭',
    currencyCode: 'LAK',
    flag: '🇱🇦',
  },
  {
    country: 'Caribbean Netherlands',
    language: 'English',
    cca2: 'BQ',
    ccn3: '535',
    cca3: 'BES',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇧🇶',
  },
  {
    country: 'Uganda',
    language: 'English',
    cca2: 'UG',
    ccn3: '800',
    cca3: 'UGA',
    cioc: 'UGA',
    currency: 'Ugandan shilling',
    currencySymbol: 'Sh',
    currencyCode: 'UGX',
    flag: '🇺🇬',
  },
  {
    country: 'Andorra',
    language: 'Catalan',
    cca2: 'AD',
    ccn3: '020',
    cca3: 'AND',
    cioc: 'AND',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇦🇩',
  },
  {
    country: 'Burundi',
    language: 'French',
    cca2: 'BI',
    ccn3: '108',
    cca3: 'BDI',
    cioc: 'BDI',
    currency: 'Burundian franc',
    currencySymbol: 'Fr',
    currencyCode: 'BIF',
    flag: '🇧🇮',
  },
  {
    country: 'South Africa',
    language: 'Afrikaans',
    cca2: 'ZA',
    ccn3: '710',
    cca3: 'ZAF',
    cioc: 'RSA',
    currency: 'South African rand',
    currencySymbol: 'R',
    currencyCode: 'ZAR',
    flag: '🇿🇦',
  },
  {
    country: 'France',
    language: 'French',
    cca2: 'FR',
    ccn3: '250',
    cca3: 'FRA',
    cioc: 'FRA',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇫🇷',
  },
  {
    country: 'Libya',
    language: 'Arabic',
    cca2: 'LY',
    ccn3: '434',
    cca3: 'LBY',
    cioc: 'LBA',
    currency: 'Libyan dinar',
    currencySymbol: 'ل.د',
    currencyCode: 'LYD',
    flag: '🇱🇾',
  },
  {
    country: 'Mexico',
    language: 'Spanish',
    cca2: 'MX',
    ccn3: '484',
    cca3: 'MEX',
    cioc: 'MEX',
    currency: 'Mexican peso',
    currencySymbol: '$',
    currencyCode: 'MXN',
    flag: '🇲🇽',
  },
  {
    country: 'Gabon',
    language: 'French',
    cca2: 'GA',
    ccn3: '266',
    cca3: 'GAB',
    cioc: 'GAB',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇬🇦',
  },
  {
    country: 'Northern Mariana Islands',
    language: 'Carolinian',
    cca2: 'MP',
    ccn3: '580',
    cca3: 'MNP',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇲🇵',
  },
  {
    country: 'North Macedonia',
    language: 'Macedonian',
    cca2: 'MK',
    ccn3: '807',
    cca3: 'MKD',
    cioc: 'MKD',
    currency: 'denar',
    currencySymbol: 'den',
    currencyCode: 'MKD',
    flag: '🇲🇰',
  },
  {
    country: 'China',
    language: 'Chinese',
    cca2: 'CN',
    ccn3: '156',
    cca3: 'CHN',
    cioc: 'CHN',
    currency: 'Chinese yuan',
    currencySymbol: '¥',
    currencyCode: 'CNY',
    flag: '🇨🇳',
  },
  {
    country: 'Yemen',
    language: 'Arabic',
    cca2: 'YE',
    ccn3: '887',
    cca3: 'YEM',
    cioc: 'YEM',
    currency: 'Yemeni rial',
    currencySymbol: '﷼',
    currencyCode: 'YER',
    flag: '🇾🇪',
  },
  {
    country: 'Saint Barthélemy',
    language: 'French',
    cca2: 'BL',
    ccn3: '652',
    cca3: 'BLM',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇧🇱',
  },
  {
    country: 'Guernsey',
    language: 'English',
    cca2: 'GG',
    ccn3: '831',
    cca3: 'GGY',
    currency: 'British pound',
    currencySymbol: '£',
    currencyCode: 'GBP',
    flag: '🇬🇬',
  },
  {
    country: 'Solomon Islands',
    language: 'English',
    cca2: 'SB',
    ccn3: '090',
    cca3: 'SLB',
    cioc: 'SOL',
    currency: 'Solomon Islands dollar',
    currencySymbol: '$',
    currencyCode: 'SBD',
    flag: '🇸🇧',
  },
  {
    country: 'Svalbard and Jan Mayen',
    language: 'Norwegian',
    cca2: 'SJ',
    ccn3: '744',
    cca3: 'SJM',
    currency: 'krone',
    currencySymbol: 'kr',
    currencyCode: 'NOK',
    flag: '🇸🇯',
  },
  {
    country: 'Faroe Islands',
    language: 'Danish',
    cca2: 'FO',
    ccn3: '234',
    cca3: 'FRO',
    currency: 'Danish krone',
    currencySymbol: 'kr',
    currencyCode: 'DKK',
    flag: '🇫🇴',
  },
  {
    country: 'Uzbekistan',
    language: 'Russian',
    cca2: 'UZ',
    ccn3: '860',
    cca3: 'UZB',
    cioc: 'UZB',
    currency: 'Uzbekistani soʻm',
    currencySymbol: "so'm",
    currencyCode: 'UZS',
    flag: '🇺🇿',
  },
  {
    country: 'Egypt',
    language: 'Arabic',
    cca2: 'EG',
    ccn3: '818',
    cca3: 'EGY',
    cioc: 'EGY',
    currency: 'Egyptian pound',
    currencySymbol: '£',
    currencyCode: 'EGP',
    flag: '🇪🇬',
  },
  {
    country: 'Senegal',
    language: 'French',
    cca2: 'SN',
    ccn3: '686',
    cca3: 'SEN',
    cioc: 'SEN',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇸🇳',
  },
  {
    country: 'Sri Lanka',
    language: 'Sinhala',
    cca2: 'LK',
    ccn3: '144',
    cca3: 'LKA',
    cioc: 'SRI',
    currency: 'Sri Lankan rupee',
    currencySymbol: 'Rs  රු',
    currencyCode: 'LKR',
    flag: '🇱🇰',
  },
  {
    country: 'Palestine',
    language: 'Arabic',
    cca2: 'PS',
    ccn3: '275',
    cca3: 'PSE',
    cioc: 'PLE',
    currency: 'Egyptian pound',
    currencySymbol: 'E£',
    currencyCode: 'EGP',
    flag: '🇵🇸',
  },
  {
    country: 'Bangladesh',
    language: 'Bengali',
    cca2: 'BD',
    ccn3: '050',
    cca3: 'BGD',
    cioc: 'BAN',
    currency: 'Bangladeshi taka',
    currencySymbol: '৳',
    currencyCode: 'BDT',
    flag: '🇧🇩',
  },
  {
    country: 'Peru',
    language: 'Aymara',
    cca2: 'PE',
    ccn3: '604',
    cca3: 'PER',
    cioc: 'PER',
    currency: 'Peruvian sol',
    currencySymbol: 'S/ ',
    currencyCode: 'PEN',
    flag: '🇵🇪',
  },
  {
    country: 'Singapore',
    language: 'English',
    cca2: 'SG',
    ccn3: '702',
    cca3: 'SGP',
    cioc: 'SGP',
    currency: 'Singapore dollar',
    currencySymbol: '$',
    currencyCode: 'SGD',
    flag: '🇸🇬',
  },
  {
    country: 'Turkey',
    language: 'Turkish',
    cca2: 'TR',
    ccn3: '792',
    cca3: 'TUR',
    cioc: 'TUR',
    currency: 'Turkish lira',
    currencySymbol: '₺',
    currencyCode: 'TRY',
    flag: '🇹🇷',
  },
  {
    country: 'Afghanistan',
    language: 'Dari',
    cca2: 'AF',
    ccn3: '004',
    cca3: 'AFG',
    cioc: 'AFG',
    currency: 'Afghan afghani',
    currencySymbol: '؋',
    currencyCode: 'AFN',
    flag: '🇦🇫',
  },
  {
    country: 'Aruba',
    language: 'Dutch',
    cca2: 'AW',
    ccn3: '533',
    cca3: 'ABW',
    cioc: 'ARU',
    currency: 'Aruban florin',
    currencySymbol: 'ƒ',
    currencyCode: 'AWG',
    flag: '🇦🇼',
  },
  {
    country: 'Cook Islands',
    language: 'English',
    cca2: 'CK',
    ccn3: '184',
    cca3: 'COK',
    cioc: 'COK',
    currency: 'Cook Islands dollar',
    currencySymbol: '$',
    currencyCode: 'CKD',
    flag: '🇨🇰',
  },
  {
    country: 'United Kingdom',
    language: 'English',
    cca2: 'GB',
    ccn3: '826',
    cca3: 'GBR',
    cioc: 'GBR',
    currency: 'British pound',
    currencySymbol: '£',
    currencyCode: 'GBP',
    flag: '🇬🇧',
  },
  {
    country: 'Zambia',
    language: 'English',
    cca2: 'ZM',
    ccn3: '894',
    cca3: 'ZMB',
    cioc: 'ZAM',
    currency: 'Zambian kwacha',
    currencySymbol: 'ZK',
    currencyCode: 'ZMW',
    flag: '🇿🇲',
  },
  {
    country: 'Finland',
    language: 'Finnish',
    cca2: 'FI',
    ccn3: '246',
    cca3: 'FIN',
    cioc: 'FIN',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇫🇮',
  },
  {
    country: 'Niger',
    language: 'French',
    cca2: 'NE',
    ccn3: '562',
    cca3: 'NER',
    cioc: 'NIG',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇳🇪',
  },
  {
    country: 'Christmas Island',
    language: 'English',
    cca2: 'CX',
    ccn3: '162',
    cca3: 'CXR',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇨🇽',
  },
  {
    country: 'Tokelau',
    language: 'English',
    cca2: 'TK',
    ccn3: '772',
    cca3: 'TKL',
    currency: 'New Zealand dollar',
    currencySymbol: '$',
    currencyCode: 'NZD',
    flag: '🇹🇰',
  },
  {
    country: 'Guinea-Bissau',
    language: 'Portuguese',
    cca2: 'GW',
    ccn3: '624',
    cca3: 'GNB',
    cioc: 'GBS',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇬🇼',
  },
  {
    country: 'Azerbaijan',
    language: 'Azerbaijani',
    cca2: 'AZ',
    ccn3: '031',
    cca3: 'AZE',
    cioc: 'AZE',
    currency: 'Azerbaijani manat',
    currencySymbol: '₼',
    currencyCode: 'AZN',
    flag: '🇦🇿',
  },
  {
    country: 'Réunion',
    language: 'French',
    cca2: 'RE',
    ccn3: '638',
    cca3: 'REU',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇷🇪',
  },
  {
    country: 'Djibouti',
    language: 'Arabic',
    cca2: 'DJ',
    ccn3: '262',
    cca3: 'DJI',
    cioc: 'DJI',
    currency: 'Djiboutian franc',
    currencySymbol: 'Fr',
    currencyCode: 'DJF',
    flag: '🇩🇯',
  },
  {
    country: 'North Korea',
    language: 'Korean',
    cca2: 'KP',
    ccn3: '408',
    cca3: 'PRK',
    cioc: 'PRK',
    currency: 'North Korean won',
    currencySymbol: '₩',
    currencyCode: 'KPW',
    flag: '🇰🇵',
  },
  {
    country: 'Mauritius',
    language: 'English',
    cca2: 'MU',
    ccn3: '480',
    cca3: 'MUS',
    cioc: 'MRI',
    currency: 'Mauritian rupee',
    currencySymbol: '₨',
    currencyCode: 'MUR',
    flag: '🇲🇺',
  },
  {
    country: 'Montserrat',
    language: 'English',
    cca2: 'MS',
    ccn3: '500',
    cca3: 'MSR',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇲🇸',
  },
  {
    country: 'United States Virgin Islands',
    language: 'English',
    cca2: 'VI',
    ccn3: '850',
    cca3: 'VIR',
    cioc: 'ISV',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇻🇮',
  },
  {
    country: 'Colombia',
    language: 'Spanish',
    cca2: 'CO',
    ccn3: '170',
    cca3: 'COL',
    cioc: 'COL',
    currency: 'Colombian peso',
    currencySymbol: '$',
    currencyCode: 'COP',
    flag: '🇨🇴',
  },
  {
    country: 'Greece',
    language: 'Greek',
    cca2: 'GR',
    ccn3: '300',
    cca3: 'GRC',
    cioc: 'GRE',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇬🇷',
  },
  {
    country: 'Croatia',
    language: 'Croatian',
    cca2: 'HR',
    ccn3: '191',
    cca3: 'HRV',
    cioc: 'CRO',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇭🇷',
  },
  {
    country: 'Morocco',
    language: 'Arabic',
    cca2: 'MA',
    ccn3: '504',
    cca3: 'MAR',
    cioc: 'MAR',
    currency: 'Moroccan dirham',
    currencySymbol: 'د.م.',
    currencyCode: 'MAD',
    flag: '🇲🇦',
  },
  {
    country: 'Algeria',
    language: 'Arabic',
    cca2: 'DZ',
    ccn3: '012',
    cca3: 'DZA',
    cioc: 'ALG',
    currency: 'Algerian dinar',
    currencySymbol: 'د.ج',
    currencyCode: 'DZD',
    flag: '🇩🇿',
  },
  {
    country: 'Antarctica',
    language: 'Unknown',
    cca2: 'AQ',
    ccn3: '010',
    cca3: 'ATA',
    currency: 'Unknown',
    currencySymbol: 'Unknown',
    currencyCode: 'N/A',
    flag: '🇦🇶',
  },
  {
    country: 'Netherlands',
    language: 'Dutch',
    cca2: 'NL',
    ccn3: '528',
    cca3: 'NLD',
    cioc: 'NED',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇳🇱',
  },
  {
    country: 'Sudan',
    language: 'Arabic',
    cca2: 'SD',
    ccn3: '729',
    cca3: 'SDN',
    cioc: 'SUD',
    currency: 'Sudanese pound',
    currencySymbol: 'ج.س',
    currencyCode: 'SDG',
    flag: '🇸🇩',
  },
  {
    country: 'Fiji',
    language: 'English',
    cca2: 'FJ',
    ccn3: '242',
    cca3: 'FJI',
    cioc: 'FIJ',
    currency: 'Fijian dollar',
    currencySymbol: '$',
    currencyCode: 'FJD',
    flag: '🇫🇯',
  },
  {
    country: 'Liechtenstein',
    language: 'German',
    cca2: 'LI',
    ccn3: '438',
    cca3: 'LIE',
    cioc: 'LIE',
    currency: 'Swiss franc',
    currencySymbol: 'Fr',
    currencyCode: 'CHF',
    flag: '🇱🇮',
  },
  {
    country: 'Nepal',
    language: 'Nepali',
    cca2: 'NP',
    ccn3: '524',
    cca3: 'NPL',
    cioc: 'NEP',
    currency: 'Nepalese rupee',
    currencySymbol: '₨',
    currencyCode: 'NPR',
    flag: '🇳🇵',
  },
  {
    country: 'Puerto Rico',
    language: 'English',
    cca2: 'PR',
    ccn3: '630',
    cca3: 'PRI',
    cioc: 'PUR',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇵🇷',
  },
  {
    country: 'Georgia',
    language: 'Georgian',
    cca2: 'GE',
    ccn3: '268',
    cca3: 'GEO',
    cioc: 'GEO',
    currency: 'lari',
    currencySymbol: '₾',
    currencyCode: 'GEL',
    flag: '🇬🇪',
  },
  {
    country: 'Pakistan',
    language: 'English',
    cca2: 'PK',
    ccn3: '586',
    cca3: 'PAK',
    cioc: 'PAK',
    currency: 'Pakistani rupee',
    currencySymbol: '₨',
    currencyCode: 'PKR',
    flag: '🇵🇰',
  },
  {
    country: 'Monaco',
    language: 'French',
    cca2: 'MC',
    ccn3: '492',
    cca3: 'MCO',
    cioc: 'MON',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇲🇨',
  },
  {
    country: 'Botswana',
    language: 'English',
    cca2: 'BW',
    ccn3: '072',
    cca3: 'BWA',
    cioc: 'BOT',
    currency: 'Botswana pula',
    currencySymbol: 'P',
    currencyCode: 'BWP',
    flag: '🇧🇼',
  },
  {
    country: 'Lebanon',
    language: 'Arabic',
    cca2: 'LB',
    ccn3: '422',
    cca3: 'LBN',
    cioc: 'LBN',
    currency: 'Lebanese pound',
    currencySymbol: 'ل.ل',
    currencyCode: 'LBP',
    flag: '🇱🇧',
  },
  {
    country: 'Papua New Guinea',
    language: 'English',
    cca2: 'PG',
    ccn3: '598',
    cca3: 'PNG',
    cioc: 'PNG',
    currency: 'Papua New Guinean kina',
    currencySymbol: 'K',
    currencyCode: 'PGK',
    flag: '🇵🇬',
  },
  {
    country: 'Mayotte',
    language: 'French',
    cca2: 'YT',
    ccn3: '175',
    cca3: 'MYT',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇾🇹',
  },
  {
    country: 'Dominican Republic',
    language: 'Spanish',
    cca2: 'DO',
    ccn3: '214',
    cca3: 'DOM',
    cioc: 'DOM',
    currency: 'Dominican peso',
    currencySymbol: '$',
    currencyCode: 'DOP',
    flag: '🇩🇴',
  },
  {
    country: 'Norfolk Island',
    language: 'English',
    cca2: 'NF',
    ccn3: '574',
    cca3: 'NFK',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇳🇫',
  },
  {
    country: 'Bouvet Island',
    language: 'Norwegian',
    cca2: 'BV',
    ccn3: '074',
    cca3: 'BVT',
    currency: 'Unknown',
    currencySymbol: 'Unknown',
    currencyCode: 'N/A',
    flag: '🇧🇻',
  },
  {
    country: 'Qatar',
    language: 'Arabic',
    cca2: 'QA',
    ccn3: '634',
    cca3: 'QAT',
    cioc: 'QAT',
    currency: 'Qatari riyal',
    currencySymbol: 'ر.ق',
    currencyCode: 'QAR',
    flag: '🇶🇦',
  },
  {
    country: 'Madagascar',
    language: 'French',
    cca2: 'MG',
    ccn3: '450',
    cca3: 'MDG',
    cioc: 'MAD',
    currency: 'Malagasy ariary',
    currencySymbol: 'Ar',
    currencyCode: 'MGA',
    flag: '🇲🇬',
  },
  {
    country: 'India',
    language: 'English',
    cca2: 'IN',
    ccn3: '356',
    cca3: 'IND',
    cioc: 'IND',
    currency: 'Indian rupee',
    currencySymbol: '₹',
    currencyCode: 'INR',
    flag: '🇮🇳',
  },
  {
    country: 'Syria',
    language: 'Arabic',
    cca2: 'SY',
    ccn3: '760',
    cca3: 'SYR',
    cioc: 'SYR',
    currency: 'Syrian pound',
    currencySymbol: '£',
    currencyCode: 'SYP',
    flag: '🇸🇾',
  },
  {
    country: 'Montenegro',
    language: 'Montenegrin',
    cca2: 'ME',
    ccn3: '499',
    cca3: 'MNE',
    cioc: 'MNE',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇲🇪',
  },
  {
    country: 'Eswatini',
    language: 'English',
    cca2: 'SZ',
    ccn3: '748',
    cca3: 'SWZ',
    cioc: 'SWZ',
    currency: 'Swazi lilangeni',
    currencySymbol: 'L',
    currencyCode: 'SZL',
    flag: '🇸🇿',
  },
  {
    country: 'Paraguay',
    language: 'Guaraní',
    cca2: 'PY',
    ccn3: '600',
    cca3: 'PRY',
    cioc: 'PAR',
    currency: 'Paraguayan guaraní',
    currencySymbol: '₲',
    currencyCode: 'PYG',
    flag: '🇵🇾',
  },
  {
    country: 'El Salvador',
    language: 'Spanish',
    cca2: 'SV',
    ccn3: '222',
    cca3: 'SLV',
    cioc: 'ESA',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇸🇻',
  },
  {
    country: 'Ukraine',
    language: 'Ukrainian',
    cca2: 'UA',
    ccn3: '804',
    cca3: 'UKR',
    cioc: 'UKR',
    currency: 'Ukrainian hryvnia',
    currencySymbol: '₴',
    currencyCode: 'UAH',
    flag: '🇺🇦',
  },
  {
    country: 'Isle of Man',
    language: 'English',
    cca2: 'IM',
    ccn3: '833',
    cca3: 'IMN',
    currency: 'British pound',
    currencySymbol: '£',
    currencyCode: 'GBP',
    flag: '🇮🇲',
  },
  {
    country: 'Namibia',
    language: 'Afrikaans',
    cca2: 'NA',
    ccn3: '516',
    cca3: 'NAM',
    cioc: 'NAM',
    currency: 'Namibian dollar',
    currencySymbol: '$',
    currencyCode: 'NAD',
    flag: '🇳🇦',
  },
  {
    country: 'United Arab Emirates',
    language: 'Arabic',
    cca2: 'AE',
    ccn3: '784',
    cca3: 'ARE',
    cioc: 'UAE',
    currency: 'United Arab Emirates dirham',
    currencySymbol: 'د.إ',
    currencyCode: 'AED',
    flag: '🇦🇪',
  },
  {
    country: 'Bulgaria',
    language: 'Bulgarian',
    cca2: 'BG',
    ccn3: '100',
    cca3: 'BGR',
    cioc: 'BUL',
    currency: 'Bulgarian lev',
    currencySymbol: 'лв',
    currencyCode: 'BGN',
    flag: '🇧🇬',
  },
  {
    country: 'Greenland',
    language: 'Greenlandic',
    cca2: 'GL',
    ccn3: '304',
    cca3: 'GRL',
    currency: 'krone',
    currencySymbol: 'kr.',
    currencyCode: 'DKK',
    flag: '🇬🇱',
  },
  {
    country: 'Germany',
    language: 'German',
    cca2: 'DE',
    ccn3: '276',
    cca3: 'DEU',
    cioc: 'GER',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇩🇪',
  },
  {
    country: 'Cambodia',
    language: 'Khmer',
    cca2: 'KH',
    ccn3: '116',
    cca3: 'KHM',
    cioc: 'CAM',
    currency: 'Cambodian riel',
    currencySymbol: '៛',
    currencyCode: 'KHR',
    flag: '🇰🇭',
  },
  {
    country: 'Iraq',
    language: 'Arabic',
    cca2: 'IQ',
    ccn3: '368',
    cca3: 'IRQ',
    cioc: 'IRQ',
    currency: 'Iraqi dinar',
    currencySymbol: 'ع.د',
    currencyCode: 'IQD',
    flag: '🇮🇶',
  },
  {
    country: 'French Southern and Antarctic Lands',
    language: 'French',
    cca2: 'TF',
    ccn3: '260',
    cca3: 'ATF',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇹🇫',
  },
  {
    country: 'Sweden',
    language: 'Swedish',
    cca2: 'SE',
    ccn3: '752',
    cca3: 'SWE',
    cioc: 'SWE',
    currency: 'Swedish krona',
    currencySymbol: 'kr',
    currencyCode: 'SEK',
    flag: '🇸🇪',
  },
  {
    country: 'Cuba',
    language: 'Spanish',
    cca2: 'CU',
    ccn3: '192',
    cca3: 'CUB',
    cioc: 'CUB',
    currency: 'Cuban convertible peso',
    currencySymbol: '$',
    currencyCode: 'CUC',
    flag: '🇨🇺',
  },
  {
    country: 'Kyrgyzstan',
    language: 'Kyrgyz',
    cca2: 'KG',
    ccn3: '417',
    cca3: 'KGZ',
    cioc: 'KGZ',
    currency: 'Kyrgyzstani som',
    currencySymbol: 'с',
    currencyCode: 'KGS',
    flag: '🇰🇬',
  },
  {
    country: 'Russia',
    language: 'Russian',
    cca2: 'RU',
    ccn3: '643',
    cca3: 'RUS',
    cioc: 'RUS',
    currency: 'Russian ruble',
    currencySymbol: '₽',
    currencyCode: 'RUB',
    flag: '🇷🇺',
  },
  {
    country: 'Malaysia',
    language: 'English',
    cca2: 'MY',
    ccn3: '458',
    cca3: 'MYS',
    cioc: 'MAS',
    currency: 'Malaysian ringgit',
    currencySymbol: 'RM',
    currencyCode: 'MYR',
    flag: '🇲🇾',
  },
  {
    country: 'São Tomé and Príncipe',
    language: 'Portuguese',
    cca2: 'ST',
    ccn3: '678',
    cca3: 'STP',
    cioc: 'STP',
    currency: 'São Tomé and Príncipe dobra',
    currencySymbol: 'Db',
    currencyCode: 'STN',
    flag: '🇸🇹',
  },
  {
    country: 'Cyprus',
    language: 'Greek',
    cca2: 'CY',
    ccn3: '196',
    cca3: 'CYP',
    cioc: 'CYP',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇨🇾',
  },
  {
    country: 'Canada',
    language: 'English',
    cca2: 'CA',
    ccn3: '124',
    cca3: 'CAN',
    cioc: 'CAN',
    currency: 'Canadian dollar',
    currencySymbol: '$',
    currencyCode: 'CAD',
    flag: '🇨🇦',
  },
  {
    country: 'Malawi',
    language: 'English',
    cca2: 'MW',
    ccn3: '454',
    cca3: 'MWI',
    cioc: 'MAW',
    currency: 'Malawian kwacha',
    currencySymbol: 'MK',
    currencyCode: 'MWK',
    flag: '🇲🇼',
  },
  {
    country: 'Saudi Arabia',
    language: 'Arabic',
    cca2: 'SA',
    ccn3: '682',
    cca3: 'SAU',
    cioc: 'KSA',
    currency: 'Saudi riyal',
    currencySymbol: 'ر.س',
    currencyCode: 'SAR',
    flag: '🇸🇦',
  },
  {
    country: 'Bosnia and Herzegovina',
    language: 'Bosnian',
    cca2: 'BA',
    ccn3: '070',
    cca3: 'BIH',
    cioc: 'BIH',
    currency: 'Bosnia and Herzegovina convertible mark',
    currencySymbol: 'KM',
    currencyCode: 'BAM',
    flag: '🇧🇦',
  },
  {
    country: 'Ethiopia',
    language: 'Amharic',
    cca2: 'ET',
    ccn3: '231',
    cca3: 'ETH',
    cioc: 'ETH',
    currency: 'Ethiopian birr',
    currencySymbol: 'Br',
    currencyCode: 'ETB',
    flag: '🇪🇹',
  },
  {
    country: 'Spain',
    language: 'Spanish',
    cca2: 'ES',
    ccn3: '724',
    cca3: 'ESP',
    cioc: 'ESP',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇪🇸',
  },
  {
    country: 'Slovenia',
    language: 'Slovene',
    cca2: 'SI',
    ccn3: '705',
    cca3: 'SVN',
    cioc: 'SLO',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇸🇮',
  },
  {
    country: 'Oman',
    language: 'Arabic',
    cca2: 'OM',
    ccn3: '512',
    cca3: 'OMN',
    cioc: 'OMA',
    currency: 'Omani rial',
    currencySymbol: 'ر.ع.',
    currencyCode: 'OMR',
    flag: '🇴🇲',
  },
  {
    country: 'Saint Pierre and Miquelon',
    language: 'French',
    cca2: 'PM',
    ccn3: '666',
    cca3: 'SPM',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇵🇲',
  },
  {
    country: 'Macau',
    language: 'Portuguese',
    cca2: 'MO',
    ccn3: '446',
    cca3: 'MAC',
    currency: 'Macanese pataca',
    currencySymbol: 'P',
    currencyCode: 'MOP',
    flag: '🇲🇴',
  },
  {
    country: 'San Marino',
    language: 'Italian',
    cca2: 'SM',
    ccn3: '674',
    cca3: 'SMR',
    cioc: 'SMR',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇸🇲',
  },
  {
    country: 'Lesotho',
    language: 'English',
    cca2: 'LS',
    ccn3: '426',
    cca3: 'LSO',
    cioc: 'LES',
    currency: 'Lesotho loti',
    currencySymbol: 'L',
    currencyCode: 'LSL',
    flag: '🇱🇸',
  },
  {
    country: 'Marshall Islands',
    language: 'English',
    cca2: 'MH',
    ccn3: '584',
    cca3: 'MHL',
    cioc: 'MHL',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇲🇭',
  },
  {
    country: 'Sint Maarten',
    language: 'English',
    cca2: 'SX',
    ccn3: '534',
    cca3: 'SXM',
    currency: 'Netherlands Antillean guilder',
    currencySymbol: 'ƒ',
    currencyCode: 'ANG',
    flag: '🇸🇽',
  },
  {
    country: 'Iceland',
    language: 'Icelandic',
    cca2: 'IS',
    ccn3: '352',
    cca3: 'ISL',
    cioc: 'ISL',
    currency: 'Icelandic króna',
    currencySymbol: 'kr',
    currencyCode: 'ISK',
    flag: '🇮🇸',
  },
  {
    country: 'Luxembourg',
    language: 'German',
    cca2: 'LU',
    ccn3: '442',
    cca3: 'LUX',
    cioc: 'LUX',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇱🇺',
  },
  {
    country: 'Argentina',
    language: 'Guaraní',
    cca2: 'AR',
    ccn3: '032',
    cca3: 'ARG',
    cioc: 'ARG',
    currency: 'Argentine peso',
    currencySymbol: '$',
    currencyCode: 'ARS',
    flag: '🇦🇷',
  },
  {
    country: 'Turks and Caicos Islands',
    language: 'English',
    cca2: 'TC',
    ccn3: '796',
    cca3: 'TCA',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇹🇨',
  },
  {
    country: 'Nauru',
    language: 'English',
    cca2: 'NR',
    ccn3: '520',
    cca3: 'NRU',
    cioc: 'NRU',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇳🇷',
  },
  {
    country: 'Cocos (Keeling) Islands',
    language: 'English',
    cca2: 'CC',
    ccn3: '166',
    cca3: 'CCK',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇨🇨',
  },
  {
    country: 'Western Sahara',
    language: 'Berber',
    cca2: 'EH',
    ccn3: '732',
    cca3: 'ESH',
    currency: 'Algerian dinar',
    currencySymbol: 'دج',
    currencyCode: 'DZD',
    flag: '🇪🇭',
  },
  {
    country: 'Dominica',
    language: 'English',
    cca2: 'DM',
    ccn3: '212',
    cca3: 'DMA',
    cioc: 'DMA',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇩🇲',
  },
  {
    country: 'Costa Rica',
    language: 'Spanish',
    cca2: 'CR',
    ccn3: '188',
    cca3: 'CRI',
    cioc: 'CRC',
    currency: 'Costa Rican colón',
    currencySymbol: '₡',
    currencyCode: 'CRC',
    flag: '🇨🇷',
  },
  {
    country: 'Australia',
    language: 'English',
    cca2: 'AU',
    ccn3: '036',
    cca3: 'AUS',
    cioc: 'AUS',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇦🇺',
  },
  {
    country: 'Thailand',
    language: 'Thai',
    cca2: 'TH',
    ccn3: '764',
    cca3: 'THA',
    cioc: 'THA',
    currency: 'Thai baht',
    currencySymbol: '฿',
    currencyCode: 'THB',
    flag: '🇹🇭',
  },
  {
    country: 'Haiti',
    language: 'French',
    cca2: 'HT',
    ccn3: '332',
    cca3: 'HTI',
    cioc: 'HAI',
    currency: 'Haitian gourde',
    currencySymbol: 'G',
    currencyCode: 'HTG',
    flag: '🇭🇹',
  },
  {
    country: 'Tuvalu',
    language: 'English',
    cca2: 'TV',
    ccn3: '798',
    cca3: 'TUV',
    cioc: 'TUV',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇹🇻',
  },
  {
    country: 'Honduras',
    language: 'Spanish',
    cca2: 'HN',
    ccn3: '340',
    cca3: 'HND',
    cioc: 'HON',
    currency: 'Honduran lempira',
    currencySymbol: 'L',
    currencyCode: 'HNL',
    flag: '🇭🇳',
  },
  {
    country: 'Equatorial Guinea',
    language: 'French',
    cca2: 'GQ',
    ccn3: '226',
    cca3: 'GNQ',
    cioc: 'GEQ',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇬🇶',
  },
  {
    country: 'Saint Lucia',
    language: 'English',
    cca2: 'LC',
    ccn3: '662',
    cca3: 'LCA',
    cioc: 'LCA',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇱🇨',
  },
  {
    country: 'French Polynesia',
    language: 'French',
    cca2: 'PF',
    ccn3: '258',
    cca3: 'PYF',
    currency: 'CFP franc',
    currencySymbol: '₣',
    currencyCode: 'XPF',
    flag: '🇵🇫',
  },
  {
    country: 'Belarus',
    language: 'Belarusian',
    cca2: 'BY',
    ccn3: '112',
    cca3: 'BLR',
    cioc: 'BLR',
    currency: 'Belarusian ruble',
    currencySymbol: 'Br',
    currencyCode: 'BYN',
    flag: '🇧🇾',
  },
  {
    country: 'Latvia',
    language: 'Latvian',
    cca2: 'LV',
    ccn3: '428',
    cca3: 'LVA',
    cioc: 'LAT',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇱🇻',
  },
  {
    country: 'Palau',
    language: 'English',
    cca2: 'PW',
    ccn3: '585',
    cca3: 'PLW',
    cioc: 'PLW',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇵🇼',
  },
  {
    country: 'Guadeloupe',
    language: 'French',
    cca2: 'GP',
    ccn3: '312',
    cca3: 'GLP',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇬🇵',
  },
  {
    country: 'Philippines',
    language: 'English',
    cca2: 'PH',
    ccn3: '608',
    cca3: 'PHL',
    cioc: 'PHI',
    currency: 'Philippine peso',
    currencySymbol: '₱',
    currencyCode: 'PHP',
    flag: '🇵🇭',
  },
  {
    country: 'Gibraltar',
    language: 'English',
    cca2: 'GI',
    ccn3: '292',
    cca3: 'GIB',
    currency: 'Gibraltar pound',
    currencySymbol: '£',
    currencyCode: 'GIP',
    flag: '🇬🇮',
  },
  {
    country: 'Denmark',
    language: 'Danish',
    cca2: 'DK',
    ccn3: '208',
    cca3: 'DNK',
    cioc: 'DEN',
    currency: 'Danish krone',
    currencySymbol: 'kr',
    currencyCode: 'DKK',
    flag: '🇩🇰',
  },
  {
    country: 'Cameroon',
    language: 'English',
    cca2: 'CM',
    ccn3: '120',
    cca3: 'CMR',
    cioc: 'CMR',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇨🇲',
  },
  {
    country: 'Guinea',
    language: 'French',
    cca2: 'GN',
    ccn3: '324',
    cca3: 'GIN',
    cioc: 'GUI',
    currency: 'Guinean franc',
    currencySymbol: 'Fr',
    currencyCode: 'GNF',
    flag: '🇬🇳',
  },
  {
    country: 'Bahrain',
    language: 'Arabic',
    cca2: 'BH',
    ccn3: '048',
    cca3: 'BHR',
    cioc: 'BHR',
    currency: 'Bahraini dinar',
    currencySymbol: '.د.ب',
    currencyCode: 'BHD',
    flag: '🇧🇭',
  },
  {
    country: 'Suriname',
    language: 'Dutch',
    cca2: 'SR',
    ccn3: '740',
    cca3: 'SUR',
    cioc: 'SUR',
    currency: 'Surinamese dollar',
    currencySymbol: '$',
    currencyCode: 'SRD',
    flag: '🇸🇷',
  },
  {
    country: 'DR Congo',
    language: 'French',
    cca2: 'CD',
    ccn3: '180',
    cca3: 'COD',
    cioc: 'COD',
    currency: 'Congolese franc',
    currencySymbol: 'FC',
    currencyCode: 'CDF',
    flag: '🇨🇩',
  },
  {
    country: 'Somalia',
    language: 'Arabic',
    cca2: 'SO',
    ccn3: '706',
    cca3: 'SOM',
    cioc: 'SOM',
    currency: 'Somali shilling',
    currencySymbol: 'Sh',
    currencyCode: 'SOS',
    flag: '🇸🇴',
  },
  {
    country: 'Czechia',
    language: 'Czech',
    cca2: 'CZ',
    ccn3: '203',
    cca3: 'CZE',
    cioc: 'CZE',
    currency: 'Czech koruna',
    currencySymbol: 'Kč',
    currencyCode: 'CZK',
    flag: '🇨🇿',
  },
  {
    country: 'New Caledonia',
    language: 'French',
    cca2: 'NC',
    ccn3: '540',
    cca3: 'NCL',
    currency: 'CFP franc',
    currencySymbol: '₣',
    currencyCode: 'XPF',
    flag: '🇳🇨',
  },
  {
    country: 'Vanuatu',
    language: 'Bislama',
    cca2: 'VU',
    ccn3: '548',
    cca3: 'VUT',
    cioc: 'VAN',
    currency: 'Vanuatu vatu',
    currencySymbol: 'Vt',
    currencyCode: 'VUV',
    flag: '🇻🇺',
  },
  {
    country: 'Saint Helena, Ascension and Tristan da Cunha',
    language: 'English',
    cca2: 'SH',
    ccn3: '654',
    cca3: 'SHN',
    currency: 'Pound sterling',
    currencySymbol: '£',
    currencyCode: 'GBP',
    flag: '🇸🇭',
  },
  {
    country: 'Togo',
    language: 'French',
    cca2: 'TG',
    ccn3: '768',
    cca3: 'TGO',
    cioc: 'TOG',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇹🇬',
  },
  {
    country: 'British Virgin Islands',
    language: 'English',
    cca2: 'VG',
    ccn3: '092',
    cca3: 'VGB',
    cioc: 'IVB',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇻🇬',
  },
  {
    country: 'Kenya',
    language: 'English',
    cca2: 'KE',
    ccn3: '404',
    cca3: 'KEN',
    cioc: 'KEN',
    currency: 'Kenyan shilling',
    currencySymbol: 'Sh',
    currencyCode: 'KES',
    flag: '🇰🇪',
  },
  {
    country: 'Niue',
    language: 'English',
    cca2: 'NU',
    ccn3: '570',
    cca3: 'NIU',
    currency: 'New Zealand dollar',
    currencySymbol: '$',
    currencyCode: 'NZD',
    flag: '🇳🇺',
  },
  {
    country: 'Heard Island and McDonald Islands',
    language: 'English',
    cca2: 'HM',
    ccn3: '334',
    cca3: 'HMD',
    currency: 'Unknown',
    currencySymbol: 'Unknown',
    currencyCode: 'N/A',
    flag: '🇭🇲',
  },
  {
    country: 'Rwanda',
    language: 'English',
    cca2: 'RW',
    ccn3: '646',
    cca3: 'RWA',
    cioc: 'RWA',
    currency: 'Rwandan franc',
    currencySymbol: 'Fr',
    currencyCode: 'RWF',
    flag: '🇷🇼',
  },
  {
    country: 'Estonia',
    language: 'Estonian',
    cca2: 'EE',
    ccn3: '233',
    cca3: 'EST',
    cioc: 'EST',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇪🇪',
  },
  {
    country: 'Romania',
    language: 'Romanian',
    cca2: 'RO',
    ccn3: '642',
    cca3: 'ROU',
    cioc: 'ROU',
    currency: 'Romanian leu',
    currencySymbol: 'lei',
    currencyCode: 'RON',
    flag: '🇷🇴',
  },
  {
    country: 'Trinidad and Tobago',
    language: 'English',
    cca2: 'TT',
    ccn3: '780',
    cca3: 'TTO',
    cioc: 'TTO',
    currency: 'Trinidad and Tobago dollar',
    currencySymbol: '$',
    currencyCode: 'TTD',
    flag: '🇹🇹',
  },
  {
    country: 'Guyana',
    language: 'English',
    cca2: 'GY',
    ccn3: '328',
    cca3: 'GUY',
    cioc: 'GUY',
    currency: 'Guyanese dollar',
    currencySymbol: '$',
    currencyCode: 'GYD',
    flag: '🇬🇾',
  },
  {
    country: 'Timor-Leste',
    language: 'Portuguese',
    cca2: 'TL',
    ccn3: '626',
    cca3: 'TLS',
    cioc: 'TLS',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇹🇱',
  },
  {
    country: 'Vietnam',
    language: 'Vietnamese',
    cca2: 'VN',
    ccn3: '704',
    cca3: 'VNM',
    cioc: 'VIE',
    currency: 'Vietnamese đồng',
    currencySymbol: '₫',
    currencyCode: 'VND',
    flag: '🇻🇳',
  },
  {
    country: 'Uruguay',
    language: 'Spanish',
    cca2: 'UY',
    ccn3: '858',
    cca3: 'URY',
    cioc: 'URU',
    currency: 'Uruguayan peso',
    currencySymbol: '$',
    currencyCode: 'UYU',
    flag: '🇺🇾',
  },
  {
    country: 'Vatican City',
    language: 'Italian',
    cca2: 'VA',
    ccn3: '336',
    cca3: 'VAT',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇻🇦',
  },
  {
    country: 'Hong Kong',
    language: 'English',
    cca2: 'HK',
    ccn3: '344',
    cca3: 'HKG',
    cioc: 'HKG',
    currency: 'Hong Kong dollar',
    currencySymbol: '$',
    currencyCode: 'HKD',
    flag: '🇭🇰',
  },
  {
    country: 'Austria',
    language: 'German',
    cca2: 'AT',
    ccn3: '040',
    cca3: 'AUT',
    cioc: 'AUT',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇦🇹',
  },
  {
    country: 'Antigua and Barbuda',
    language: 'English',
    cca2: 'AG',
    ccn3: '028',
    cca3: 'ATG',
    cioc: 'ANT',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇦🇬',
  },
  {
    country: 'Turkmenistan',
    language: 'Russian',
    cca2: 'TM',
    ccn3: '795',
    cca3: 'TKM',
    cioc: 'TKM',
    currency: 'Turkmenistan manat',
    currencySymbol: 'm',
    currencyCode: 'TMT',
    flag: '🇹🇲',
  },
  {
    country: 'Mozambique',
    language: 'Portuguese',
    cca2: 'MZ',
    ccn3: '508',
    cca3: 'MOZ',
    cioc: 'MOZ',
    currency: 'Mozambican metical',
    currencySymbol: 'MT',
    currencyCode: 'MZN',
    flag: '🇲🇿',
  },
  {
    country: 'Panama',
    language: 'Spanish',
    cca2: 'PA',
    ccn3: '591',
    cca3: 'PAN',
    cioc: 'PAN',
    currency: 'Panamanian balboa',
    currencySymbol: 'B/.',
    currencyCode: 'PAB',
    flag: '🇵🇦',
  },
  {
    country: 'Micronesia',
    language: 'English',
    cca2: 'FM',
    ccn3: '583',
    cca3: 'FSM',
    cioc: 'FSM',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇫🇲',
  },
  {
    country: 'Ireland',
    language: 'English',
    cca2: 'IE',
    ccn3: '372',
    cca3: 'IRL',
    cioc: 'IRL',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇮🇪',
  },
  {
    country: 'Curaçao',
    language: 'English',
    cca2: 'CW',
    ccn3: '531',
    cca3: 'CUW',
    currency: 'Netherlands Antillean guilder',
    currencySymbol: 'ƒ',
    currencyCode: 'ANG',
    flag: '🇨🇼',
  },
  {
    country: 'French Guiana',
    language: 'French',
    cca2: 'GF',
    ccn3: '254',
    cca3: 'GUF',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇬🇫',
  },
  {
    country: 'Norway',
    language: 'Norwegian Nynorsk',
    cca2: 'NO',
    ccn3: '578',
    cca3: 'NOR',
    cioc: 'NOR',
    currency: 'Norwegian krone',
    currencySymbol: 'kr',
    currencyCode: 'NOK',
    flag: '🇳🇴',
  },
  {
    country: 'Åland Islands',
    language: 'Swedish',
    cca2: 'AX',
    ccn3: '248',
    cca3: 'ALA',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇦🇽',
  },
  {
    country: 'Central African Republic',
    language: 'French',
    cca2: 'CF',
    ccn3: '140',
    cca3: 'CAF',
    cioc: 'CAF',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇨🇫',
  },
  {
    country: 'Burkina Faso',
    language: 'French',
    cca2: 'BF',
    ccn3: '854',
    cca3: 'BFA',
    cioc: 'BUR',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇧🇫',
  },
  {
    country: 'Eritrea',
    language: 'Arabic',
    cca2: 'ER',
    ccn3: '232',
    cca3: 'ERI',
    cioc: 'ERI',
    currency: 'Eritrean nakfa',
    currencySymbol: 'Nfk',
    currencyCode: 'ERN',
    flag: '🇪🇷',
  },
  {
    country: 'Tanzania',
    language: 'English',
    cca2: 'TZ',
    ccn3: '834',
    cca3: 'TZA',
    cioc: 'TAN',
    currency: 'Tanzanian shilling',
    currencySymbol: 'Sh',
    currencyCode: 'TZS',
    flag: '🇹🇿',
  },
  {
    country: 'South Korea',
    language: 'Korean',
    cca2: 'KR',
    ccn3: '410',
    cca3: 'KOR',
    cioc: 'KOR',
    currency: 'South Korean won',
    currencySymbol: '₩',
    currencyCode: 'KRW',
    flag: '🇰🇷',
  },
  {
    country: 'Jordan',
    language: 'Arabic',
    cca2: 'JO',
    ccn3: '400',
    cca3: 'JOR',
    cioc: 'JOR',
    currency: 'Jordanian dinar',
    currencySymbol: 'د.ا',
    currencyCode: 'JOD',
    flag: '🇯🇴',
  },
  {
    country: 'Mauritania',
    language: 'Arabic',
    cca2: 'MR',
    ccn3: '478',
    cca3: 'MRT',
    cioc: 'MTN',
    currency: 'Mauritanian ouguiya',
    currencySymbol: 'UM',
    currencyCode: 'MRU',
    flag: '🇲🇷',
  },
  {
    country: 'Lithuania',
    language: 'Lithuanian',
    cca2: 'LT',
    ccn3: '440',
    cca3: 'LTU',
    cioc: 'LTU',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇱🇹',
  },
  {
    country: 'United States Minor Outlying Islands',
    language: 'English',
    cca2: 'UM',
    ccn3: '581',
    cca3: 'UMI',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇺🇲',
  },
  {
    country: 'Slovakia',
    language: 'Slovak',
    cca2: 'SK',
    ccn3: '703',
    cca3: 'SVK',
    cioc: 'SVK',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇸🇰',
  },
  {
    country: 'Angola',
    language: 'Portuguese',
    cca2: 'AO',
    ccn3: '024',
    cca3: 'AGO',
    cioc: 'ANG',
    currency: 'Angolan kwanza',
    currencySymbol: 'Kz',
    currencyCode: 'AOA',
    flag: '🇦🇴',
  },
  {
    country: 'Kazakhstan',
    language: 'Kazakh',
    cca2: 'KZ',
    ccn3: '398',
    cca3: 'KAZ',
    cioc: 'KAZ',
    currency: 'Kazakhstani tenge',
    currencySymbol: '₸',
    currencyCode: 'KZT',
    flag: '🇰🇿',
  },
  {
    country: 'Moldova',
    language: 'Romanian',
    cca2: 'MD',
    ccn3: '498',
    cca3: 'MDA',
    cioc: 'MDA',
    currency: 'Moldovan leu',
    currencySymbol: 'L',
    currencyCode: 'MDL',
    flag: '🇲🇩',
  },
  {
    country: 'Mali',
    language: 'French',
    cca2: 'ML',
    ccn3: '466',
    cca3: 'MLI',
    cioc: 'MLI',
    currency: 'West African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XOF',
    flag: '🇲🇱',
  },
  {
    country: 'Falkland Islands',
    language: 'English',
    cca2: 'FK',
    ccn3: '238',
    cca3: 'FLK',
    currency: 'Falkland Islands pound',
    currencySymbol: '£',
    currencyCode: 'FKP',
    flag: '🇫🇰',
  },
  {
    country: 'Armenia',
    language: 'Armenian',
    cca2: 'AM',
    ccn3: '051',
    cca3: 'ARM',
    cioc: 'ARM',
    currency: 'Armenian dram',
    currencySymbol: '֏',
    currencyCode: 'AMD',
    flag: '🇦🇲',
  },
  {
    country: 'Samoa',
    language: 'English',
    cca2: 'WS',
    ccn3: '882',
    cca3: 'WSM',
    cioc: 'SAM',
    currency: 'Samoan tālā',
    currencySymbol: 'T',
    currencyCode: 'WST',
    flag: '🇼🇸',
  },
  {
    country: 'Jersey',
    language: 'English',
    cca2: 'JE',
    ccn3: '832',
    cca3: 'JEY',
    currency: 'British pound',
    currencySymbol: '£',
    currencyCode: 'GBP',
    flag: '🇯🇪',
  },
  {
    country: 'Japan',
    language: 'Japanese',
    cca2: 'JP',
    ccn3: '392',
    cca3: 'JPN',
    cioc: 'JPN',
    currency: 'Japanese yen',
    currencySymbol: '¥',
    currencyCode: 'JPY',
    flag: '🇯🇵',
  },
  {
    country: 'Bolivia',
    language: 'Aymara',
    cca2: 'BO',
    ccn3: '068',
    cca3: 'BOL',
    cioc: 'BOL',
    currency: 'Bolivian boliviano',
    currencySymbol: 'Bs.',
    currencyCode: 'BOB',
    flag: '🇧🇴',
  },
  {
    country: 'Chile',
    language: 'Spanish',
    cca2: 'CL',
    ccn3: '152',
    cca3: 'CHL',
    cioc: 'CHI',
    currency: 'Chilean peso',
    currencySymbol: '$',
    currencyCode: 'CLP',
    flag: '🇨🇱',
  },
  {
    country: 'United States',
    language: 'English',
    cca2: 'US',
    ccn3: '840',
    cca3: 'USA',
    cioc: 'USA',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇺🇸',
  },
  {
    country: 'Saint Vincent and the Grenadines',
    language: 'English',
    cca2: 'VC',
    ccn3: '670',
    cca3: 'VCT',
    cioc: 'VIN',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇻🇨',
  },
  {
    country: 'Bermuda',
    language: 'English',
    cca2: 'BM',
    ccn3: '060',
    cca3: 'BMU',
    cioc: 'BER',
    currency: 'Bermudian dollar',
    currencySymbol: '$',
    currencyCode: 'BMD',
    flag: '🇧🇲',
  },
  {
    country: 'Seychelles',
    language: 'Seychellois Creole',
    cca2: 'SC',
    ccn3: '690',
    cca3: 'SYC',
    cioc: 'SEY',
    currency: 'Seychellois rupee',
    currencySymbol: '₨',
    currencyCode: 'SCR',
    flag: '🇸🇨',
  },
  {
    country: 'British Indian Ocean Territory',
    language: 'English',
    cca2: 'IO',
    ccn3: '086',
    cca3: 'IOT',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇮🇴',
  },
  {
    country: 'Guatemala',
    language: 'Spanish',
    cca2: 'GT',
    ccn3: '320',
    cca3: 'GTM',
    cioc: 'GUA',
    currency: 'Guatemalan quetzal',
    currencySymbol: 'Q',
    currencyCode: 'GTQ',
    flag: '🇬🇹',
  },
  {
    country: 'Ecuador',
    language: 'Spanish',
    cca2: 'EC',
    ccn3: '218',
    cca3: 'ECU',
    cioc: 'ECU',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇪🇨',
  },
  {
    country: 'Martinique',
    language: 'French',
    cca2: 'MQ',
    ccn3: '474',
    cca3: 'MTQ',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇲🇶',
  },
  {
    country: 'Tajikistan',
    language: 'Russian',
    cca2: 'TJ',
    ccn3: '762',
    cca3: 'TJK',
    cioc: 'TJK',
    currency: 'Tajikistani somoni',
    currencySymbol: 'ЅМ',
    currencyCode: 'TJS',
    flag: '🇹🇯',
  },
  {
    country: 'Malta',
    language: 'English',
    cca2: 'MT',
    ccn3: '470',
    cca3: 'MLT',
    cioc: 'MLT',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇲🇹',
  },
  {
    country: 'Gambia',
    language: 'English',
    cca2: 'GM',
    ccn3: '270',
    cca3: 'GMB',
    cioc: 'GAM',
    currency: 'dalasi',
    currencySymbol: 'D',
    currencyCode: 'GMD',
    flag: '🇬🇲',
  },
  {
    country: 'Nigeria',
    language: 'English',
    cca2: 'NG',
    ccn3: '566',
    cca3: 'NGA',
    cioc: 'NGR',
    currency: 'Nigerian naira',
    currencySymbol: '₦',
    currencyCode: 'NGN',
    flag: '🇳🇬',
  },
  {
    country: 'Bahamas',
    language: 'English',
    cca2: 'BS',
    ccn3: '044',
    cca3: 'BHS',
    cioc: 'BAH',
    currency: 'Bahamian dollar',
    currencySymbol: '$',
    currencyCode: 'BSD',
    flag: '🇧🇸',
  },
  {
    country: 'Kosovo',
    language: 'Albanian',
    cca2: 'XK',
    ccn3: 'Unknown',
    cca3: 'UNK',
    cioc: 'KOS',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇽🇰',
  },
  {
    country: 'Kuwait',
    language: 'Arabic',
    cca2: 'KW',
    ccn3: '414',
    cca3: 'KWT',
    cioc: 'KUW',
    currency: 'Kuwaiti dinar',
    currencySymbol: 'د.ك',
    currencyCode: 'KWD',
    flag: '🇰🇼',
  },
  {
    country: 'Maldives',
    language: 'Maldivian',
    cca2: 'MV',
    ccn3: '462',
    cca3: 'MDV',
    cioc: 'MDV',
    currency: 'Maldivian rufiyaa',
    currencySymbol: '.ރ',
    currencyCode: 'MVR',
    flag: '🇲🇻',
  },
  {
    country: 'South Sudan',
    language: 'English',
    cca2: 'SS',
    ccn3: '728',
    cca3: 'SSD',
    cioc: 'SSD',
    currency: 'South Sudanese pound',
    currencySymbol: '£',
    currencyCode: 'SSP',
    flag: '🇸🇸',
  },
  {
    country: 'Iran',
    language: 'Persian (Farsi)',
    cca2: 'IR',
    ccn3: '364',
    cca3: 'IRN',
    cioc: 'IRI',
    currency: 'Iranian rial',
    currencySymbol: '﷼',
    currencyCode: 'IRR',
    flag: '🇮🇷',
  },
  {
    country: 'Albania',
    language: 'Albanian',
    cca2: 'AL',
    ccn3: '008',
    cca3: 'ALB',
    cioc: 'ALB',
    currency: 'Albanian lek',
    currencySymbol: 'L',
    currencyCode: 'ALL',
    flag: '🇦🇱',
  },
  {
    country: 'Brazil',
    language: 'Portuguese',
    cca2: 'BR',
    ccn3: '076',
    cca3: 'BRA',
    cioc: 'BRA',
    currency: 'Brazilian real',
    currencySymbol: 'R$',
    currencyCode: 'BRL',
    flag: '🇧🇷',
  },
  {
    country: 'Serbia',
    language: 'Serbian',
    cca2: 'RS',
    ccn3: '688',
    cca3: 'SRB',
    cioc: 'SRB',
    currency: 'Serbian dinar',
    currencySymbol: 'дин.',
    currencyCode: 'RSD',
    flag: '🇷🇸',
  },
  {
    country: 'Belize',
    language: 'Belizean Creole',
    cca2: 'BZ',
    ccn3: '084',
    cca3: 'BLZ',
    cioc: 'BIZ',
    currency: 'Belize dollar',
    currencySymbol: '$',
    currencyCode: 'BZD',
    flag: '🇧🇿',
  },
  {
    country: 'Myanmar',
    language: 'Burmese',
    cca2: 'MM',
    ccn3: '104',
    cca3: 'MMR',
    cioc: 'MYA',
    currency: 'Burmese kyat',
    currencySymbol: 'Ks',
    currencyCode: 'MMK',
    flag: '🇲🇲',
  },
  {
    country: 'Bhutan',
    language: 'Dzongkha',
    cca2: 'BT',
    ccn3: '064',
    cca3: 'BTN',
    cioc: 'BHU',
    currency: 'Bhutanese ngultrum',
    currencySymbol: 'Nu.',
    currencyCode: 'BTN',
    flag: '🇧🇹',
  },
  {
    country: 'Venezuela',
    language: 'Spanish',
    cca2: 'VE',
    ccn3: '862',
    cca3: 'VEN',
    cioc: 'VEN',
    currency: 'Venezuelan bolívar soberano',
    currencySymbol: 'Bs.S.',
    currencyCode: 'VES',
    flag: '🇻🇪',
  },
  {
    country: 'Liberia',
    language: 'English',
    cca2: 'LR',
    ccn3: '430',
    cca3: 'LBR',
    cioc: 'LBR',
    currency: 'Liberian dollar',
    currencySymbol: '$',
    currencyCode: 'LRD',
    flag: '🇱🇷',
  },
  {
    country: 'Jamaica',
    language: 'English',
    cca2: 'JM',
    ccn3: '388',
    cca3: 'JAM',
    cioc: 'JAM',
    currency: 'Jamaican dollar',
    currencySymbol: '$',
    currencyCode: 'JMD',
    flag: '🇯🇲',
  },
  {
    country: 'Poland',
    language: 'Polish',
    cca2: 'PL',
    ccn3: '616',
    cca3: 'POL',
    cioc: 'POL',
    currency: 'Polish złoty',
    currencySymbol: 'zł',
    currencyCode: 'PLN',
    flag: '🇵🇱',
  },
  {
    country: 'Cayman Islands',
    language: 'English',
    cca2: 'KY',
    ccn3: '136',
    cca3: 'CYM',
    cioc: 'CAY',
    currency: 'Cayman Islands dollar',
    currencySymbol: '$',
    currencyCode: 'KYD',
    flag: '🇰🇾',
  },
  {
    country: 'Brunei',
    language: 'Malay',
    cca2: 'BN',
    ccn3: '096',
    cca3: 'BRN',
    cioc: 'BRU',
    currency: 'Brunei dollar',
    currencySymbol: '$',
    currencyCode: 'BND',
    flag: '🇧🇳',
  },
  {
    country: 'Comoros',
    language: 'Arabic',
    cca2: 'KM',
    ccn3: '174',
    cca3: 'COM',
    cioc: 'COM',
    currency: 'Comorian franc',
    currencySymbol: 'Fr',
    currencyCode: 'KMF',
    flag: '🇰🇲',
  },
  {
    country: 'Guam',
    language: 'Chamorro',
    cca2: 'GU',
    ccn3: '316',
    cca3: 'GUM',
    cioc: 'GUM',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇬🇺',
  },
  {
    country: 'Tonga',
    language: 'English',
    cca2: 'TO',
    ccn3: '776',
    cca3: 'TON',
    cioc: 'TGA',
    currency: 'Tongan paʻanga',
    currencySymbol: 'T$',
    currencyCode: 'TOP',
    flag: '🇹🇴',
  },
  {
    country: 'Kiribati',
    language: 'English',
    cca2: 'KI',
    ccn3: '296',
    cca3: 'KIR',
    cioc: 'KIR',
    currency: 'Australian dollar',
    currencySymbol: '$',
    currencyCode: 'AUD',
    flag: '🇰🇮',
  },
  {
    country: 'Ghana',
    language: 'English',
    cca2: 'GH',
    ccn3: '288',
    cca3: 'GHA',
    cioc: 'GHA',
    currency: 'Ghanaian cedi',
    currencySymbol: '₵',
    currencyCode: 'GHS',
    flag: '🇬🇭',
  },
  {
    country: 'Chad',
    language: 'Arabic',
    cca2: 'TD',
    ccn3: '148',
    cca3: 'TCD',
    cioc: 'CHA',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇹🇩',
  },
  {
    country: 'Zimbabwe',
    language: 'Chibarwe',
    cca2: 'ZW',
    ccn3: '716',
    cca3: 'ZWE',
    cioc: 'ZIM',
    currency: 'Zimbabwean dollar',
    currencySymbol: '$',
    currencyCode: 'ZWL',
    flag: '🇿🇼',
  },
  {
    country: 'Saint Martin',
    language: 'French',
    cca2: 'MF',
    ccn3: '663',
    cca3: 'MAF',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇲🇫',
  },
  {
    country: 'Mongolia',
    language: 'Mongolian',
    cca2: 'MN',
    ccn3: '496',
    cca3: 'MNG',
    cioc: 'MGL',
    currency: 'Mongolian tögrög',
    currencySymbol: '₮',
    currencyCode: 'MNT',
    flag: '🇲🇳',
  },
  {
    country: 'Portugal',
    language: 'Portuguese',
    cca2: 'PT',
    ccn3: '620',
    cca3: 'PRT',
    cioc: 'POR',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇵🇹',
  },
  {
    country: 'American Samoa',
    language: 'English',
    cca2: 'AS',
    ccn3: '016',
    cca3: 'ASM',
    cioc: 'ASA',
    currency: 'United States dollar',
    currencySymbol: '$',
    currencyCode: 'USD',
    flag: '🇦🇸',
  },
  {
    country: 'Republic of the Congo',
    language: 'French',
    cca2: 'CG',
    ccn3: '178',
    cca3: 'COG',
    cioc: 'CGO',
    currency: 'Central African CFA franc',
    currencySymbol: 'Fr',
    currencyCode: 'XAF',
    flag: '🇨🇬',
  },
  {
    country: 'Belgium',
    language: 'German',
    cca2: 'BE',
    ccn3: '056',
    cca3: 'BEL',
    cioc: 'BEL',
    currency: 'Euro',
    currencySymbol: '€',
    currencyCode: 'EUR',
    flag: '🇧🇪',
  },
  {
    country: 'Israel',
    language: 'Arabic',
    cca2: 'IL',
    ccn3: '376',
    cca3: 'ISR',
    cioc: 'ISR',
    currency: 'Israeli new shekel',
    currencySymbol: '₪',
    currencyCode: 'ILS',
    flag: '🇮🇱',
  },
  {
    country: 'New Zealand',
    language: 'English',
    cca2: 'NZ',
    ccn3: '554',
    cca3: 'NZL',
    cioc: 'NZL',
    currency: 'New Zealand dollar',
    currencySymbol: '$',
    currencyCode: 'NZD',
    flag: '🇳🇿',
  },
  {
    country: 'Nicaragua',
    language: 'Spanish',
    cca2: 'NI',
    ccn3: '558',
    cca3: 'NIC',
    cioc: 'NCA',
    currency: 'Nicaraguan córdoba',
    currencySymbol: 'C$',
    currencyCode: 'NIO',
    flag: '🇳🇮',
  },
  {
    country: 'Anguilla',
    language: 'English',
    cca2: 'AI',
    ccn3: '660',
    cca3: 'AIA',
    currency: 'Eastern Caribbean dollar',
    currencySymbol: '$',
    currencyCode: 'XCD',
    flag: '🇦🇮',
  },
];
